version: "3.8"

services:

    mysql:
        build: ./docker/mysql
        image: mysql:8.0
        container_name: mysql
        environment:
            - MYSQL_USER=ecommerceapp
            - MYSQL_PASSWORD=ecommerceapp
            - MYSQL_DATABASE=ecommerceapp
            - MYSQL_ROOT_PASSWORD=r00t123
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./log/mysql:/var/log/mysql
