version: "3.8"

services:

    spring:
        restart: always    
        hostname: spring
        container_name: spring
        build: 
            context: ./spring
            target: test       
        ports:
            - 8000:8000
            - 8080:8080
            - 8443:8443
        volumes:
            - ./spring:/app      
        depends_on:
            - mysql

    mysql:
        build: ./mysql
        restart: always    
        hostname: mysql
        container_name: mysql
        ports:
            - 3306:3306            
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=r00t123        
            - MYSQL_USER=ecommerceapp
            - MYSQL_PASSWORD=ecommerceapp
            - MYSQL_DATABASE=ecommerceapp
        volumes:
            - ./mysql/conf.d:/etc/mysql/conf.d
            - ./mysql/initdb.d:/docker-entrypoint-initdb.d
