version: "3.8"

services:

    angular:
        build: angular
        ports:
            - 80:80
        volumes:
            - ./angular:/app
            - /app/node_modules

    spring:
        build: spring
        ports:
            - 8080:8080
        volumes:
            - ./spring:/app
        depends_on:
            - mysql

    mysql:
        build: mysql
        ports:
            - 3306:3306
