# https://mherman.org/blog/dockerizing-an-angular-app/

FROM node:18

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@15.2.4
COPY . /app

CMD ["ng", "serve"]
