FROM mysql:8.0

ENV MYSQL_ROOT_HOST %
ENV MYSQL_USER ecommerceapp
ENV MYSQL_PASSWORD ecommerceapp
ENV MYSQL_DATABASE ecommerceapp
ENV MYSQL_ALLOW_EMPTY_PASSWORD "yes"

COPY my.cnf /etc/mysql/conf.d/
COPY ./sql/ /docker-entrypoint-initdb.d/